### ISSUE TITLE
Multitouch

### ISSUE THREAD

**Issue by ItzVladik** [osudroid/osu-droid#104]
Multitouch don’t support
Multitouch doesn't work only in Osu Droid, when you start osu droid writes that multitouch is not supported and it doesn't work, but in other games it works great 
![Screenshot_20210404_171227_ru nsu ccfit zuev osuplus](https://user-images.githubusercontent.com/61982094/113509485-4e26b480-956f-11eb-8ac7-a593354b9a47.jpg)
![Screenshot_20210404_171241_com huawei android launcher](https://user-images.githubusercontent.com/61982094/113509489-4ff07800-956f-11eb-8494-2fbc0ae21698.jpg)
Device : HONOR 9S

**Comment by OsuNoobForever** [comment]
Have you tried to turn off your gestures in your options menu? Usually issues like this one are related to the gestures which are turned on by default.

**Comment by OsuNoobForever** [comment]
Also from what I've read you are using a Huawei device. Huawei devices are well known for having input delay and non-registered input. I'm also using a Huawei device and have some of this issues like delay and multi-touch issues.

**Comment by ItzVladik** [comment]
> Have you tried to turn off your gestures in your options menu? Usually issues like this one are related to the gestures which are turned on by default.

Gestures are off

**Comment by ItzVladik** [comment]
I

> Also from what I've read you are using a Huawei device. Huawei devices are well known for having input delay and non-registered input. I'm also using a Huawei device and I also experience some of this issues like delay and multi-touch issues.

But why, then in other multitouch games works well and only in Osu it does not work?

**Comment by OsuNoobForever** [comment]
I'm not really sure what causes these issues. It is true that in other multi gesture games the issues are nonexistent. Even I don't experience any issues with other games. It may be something with the way the game processes inputs?

**Comment by ammarasyad** [comment]
It is probably due to how o!d detects multitouch support.
```
public static boolean isSupported(final Context pContext) {
  if(SUPPORTED == null) {
    SUPPORTED = SystemUtils.isAndroidVersionOrHigher(Build.VERSION_CODES.ECLAIR) && SystemUtils.hasSystemFeature(pContext, PackageManager.FEATURE_TOUCHSCREEN_MULTITOUCH);
  }
    return SUPPORTED;
}
```
Huawei phones probably don't report `FEATURE_TOUCHSCREEN_MULTITOUCH` for some reason. This issue is prevalent on Huawei phones, so it could be a vendor-specific problem, or the ROM.

**Comment by Etunts** [comment]
can you provide me the latest build without multitouch checks?
