### ISSUE TITLE
Game recognizes partially downloaded files as beatmap files

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#106]
Results in this error:
![image](https://user-images.githubusercontent.com/52914632/113832197-9386f400-97b2-11eb-8189-b98cbf02dec7.png)

**Comment by kairusds** [comment]
you mean it tries to import the .com.google.Chrome files?

**Comment by Rian8337** [comment]
Not always Google Chrome (or Chromium-based browser in general) since each browser has different format for partially downloaded files, but it is one of them.

To reproduce, just download a beatmap and open the game while it is still downloading.

**Comment by kairusds** [comment]
> Not always Google Chrome (or Chromium-based browser in general) since each browser has different format for partially downloaded files, but it is one of them.
> 
> To reproduce, just download a beatmap and open the game while it is still downloading (I don't know if it's reproducible via scan download or direct import, but I guess you can test).

alright I'll try checking it and see if i can fix it
