### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by Acivev** [osudroid/osu-droid#11]
**If you are good at  java or Kotlin, a pull request is much better than a feature request**
We only have a few developers, and most of them are busy. We don't have enough time to implement your feature request. So, if your are good at coding, you can try to implement your feature request youself.

**Comment by kolikisabaddev** [comment]
Add the triangles on the menu 
i don't care if its in rythm with the music or not i would just like to see them
like this
https://youtu.be/rXdBRRkP_aw

**Comment by OsuNoobForever** [comment]
Hello, I wanna request to add userpanel in-game if it's possible, I know that the account stuff is kinda complicated but I'll love to see it added in the future update!

**Comment by hanarix** [comment]
Hi, I'd like to request the addition of the AudioPlaybackCapture API to be able to capture audio directly from the game for Android 10 users.

**Comment by o-dasher** [comment]
maybe like a mod that would limit the imput to just 1 cursor so we can boost singletap players and a mod that like there's a cursor that can just be moved if you drag it and you have a position to click so it would be possible to boost both drag and singletap playstyles.

**Comment by OsuNoobForever** [comment]
Also i wanna add something else. Can you make the main menu background changable depending on the skin? It's kinda useless but i would love to see it.

**Comment by Rikopin15** [comment]
Can you make most elements skinnable including sound effects.
Also it would be convenient if we can switch skins on selection-options or on the settings panel on selection-mods

**Comment by o-dasher** [comment]
another page in mod selection for unranked mods so it doesn't become full of mods :p

**Comment by kolikisabaddev** [comment]
@o-dasher i made how your thing could look like 
![20200616_151102](https://user-images.githubusercontent.com/55196465/84778966-05a00980-afe4-11ea-9351-a56b0a30304d.png)
![20200616_151102](https://user-images.githubusercontent.com/55196465/84779001-12bcf880-afe4-11ea-95ce-1902cce28b57.png)

**Comment by o-dasher** [comment]
woi like this

**Comment by kairusds** [comment]
@hanarix got it

**Comment by kairusds** [comment]
> Hello, I wanna request to add userpanel in-game if it's possible, I know that the account stuff is kinda complicated but I'll love to see it added in the future update!

edrows doesn't like the idea of adding more in-game gui so i don't think it's possible atm

**Comment by EdrowsLuo** [comment]
> > Hello, I wanna request to add userpanel in-game if it's possible, I know that the account stuff is kinda complicated but I'll love to see it added in the future update!
> 
> edrows doesn't like the idea of adding more in-game gui so i don't think it's possible atm

I mean that we should avoid using AndEngine ui, native android style ui is welcome.
Or use the new draw interface.

**Comment by kairusds** [comment]
> > > Hello, I wanna request to add userpanel in-game if it's possible, I know that the account stuff is kinda complicated but I'll love to see it added in the future update!
> > 
> > 
> > edrows doesn't like the idea of adding more in-game gui so i don't think it's possible atm
> 
> I mean that we should avoid using AndEngine ui, native android style ui is welcome.
> Or use the new draw interface.
Oh okay, guess that clears up some of the confusion

**Comment by forgottenpeople337** [comment]
Hello, I wanna request to add Brightness option in gameplay pause it would very useful

**Comment by forgottenpeople337** [comment]
Add more ui sounds ui size maybe?

**Comment by pinSyn** [comment]
Hey, it would be nice if after you exited the pause screen, you could choose when you want to start playing. It could be the same as in pc osu, or it could be like "tap anywhere to continue playing" kind of a thing. Would be really useful

**Comment by kairusds** [comment]
> Hey, it would be nice if after you exited the pause screen, you could choose when you want to start playing. It could be the same as in pc osu, or it could be like "tap anywhere to continue playing" kind of a thing. Would be really useful

this wont be added sadly

**Comment by vorkey** [comment]
Hello, can you add option to disable animated ui, because it lower performance in my device.

**Comment by Beyley** [comment]
> Hello, I wanna request to add Brightness option in gameplay pause it would very useful

 just use the brightness on your phone settings, unless you mean gamma and it was lost in translation, which is an even bigger no

**Comment by DaddyDiegoBrando** [comment]
Would it be possible to add the cursor to auto mod & auto pilot mod? Just something nifty, also I'd say it's be rly helpful for the auto pilot mod so I have a good idea when to tap (sure the rhythm of the game is supposed to help but still)

**Comment by DaddyDiegoBrando** [comment]
Oh also can we have a proper long cursor trail like in the pc version? Idk if that will cause lag or not but it'd definitely look alot better

**Comment by Rian8337** [comment]
> Would it be possible to add the cursor to auto mod & auto pilot mod? Just something nifty, also I'd say it's be rly helpful for the auto pilot mod so I have a good idea when to tap (sure the rhythm of the game is supposed to help but still)

Already in process in #116

**Comment by LucyFurrMorningstsr** [comment]
Snaking sliders should be a separate setting from rather than being part of Complex Effects. I want to turn on Burst effects or Hit lightning but it only applies if Complex Effects is toggled - and snaking sliders makes reading 2x harder.

Separate setting to not include other playfield elements (such as healthbar, leaderboards and score) when shrinking the playfield size

**Comment by Likver** [comment]
Make an option that enable/disable the cursor only visible in replays

**Comment by GIorp3179** [comment]
Setting for the limit of cursors on screen, client sided only of course

**Comment by Beyley** [comment]
> 3rd stage when?? 

can you elaborate?

**Comment by N0tvich** [comment]
can be added to osu to play with keyboard and mouse? or is it already added

**Comment by Beyley** [comment]
> can be added to osu to play with keyboard and mouse? or is it already added

this has been discussed at length before, it would be unfair to other players, as not all have access to a bluetooth keyboard or an OTG adapter

**Comment by N0tvich** [comment]
but an otg cable is very cheap and there are already several keyboards and mice due to the pandemic

**Comment by N0tvich** [comment]
> 
but an otg cable is very cheap and there are already several keyboards and mice due to the pandemic

**Comment by Beyley** [comment]
> > 
> 
> but an otg cable is very cheap and there are already several keyboards and mice due to the pandemic

Doesnt change that its kinda a bit overpowered on certain types of maps, and would be unfair to the other players, and "its cheap" doesnt mean that its still not a paid advantage
Most of the players are very young, they likely dont have the money to buy it, it wouldnt be fair to them

**Comment by N0tvich** [comment]
In that you are absolutely right, but those people are not going to play difficult maps or rather they are never going to pass it with their fingers, and if we talk about being fair, people who have better phones or have a bigger screen should not play like this an ipad or a stylus

**Comment by N0tvich** [comment]
but then those children will want to learn to play like people who are very good on pc do and if you don't give them that game mode with keyboard they will leave the application

**Comment by Beyley** [comment]
> In that you are absolutely right, but those people are not going to play difficult maps or rather they are never going to pass it with their fingers, and if we talk about being fair, people who have better phones or have a bigger screen should not play like this an ipad or a stylus

You cant just say "all kids are bad, so its fine to restrict them from competing fairly" thats how you foster an uncompetitive unfun experience for everyone, and bigger screens do not make things easier or harder, circles are quite larger but you have to move your hands more, so you get less stamina
Stylus is different as it is inheriently worse then a finger, aside from friction

**Comment by Beyley** [comment]
> but then those children will want to learn to play like people who are very good on pc do and if you don't give them that game mode with keyboard they will leave the application

osu!droid is *not* a clone of osu!stable, it is entirely separate, if they wanna play stable on a phone with a mouse or kb, they can go to an app that is trying to be a clone of osu!stable, whether that be opsu! or osu!lazer

**Comment by N0tvich** [comment]
well it was just a suggestion and thanks for your help in my question

**Comment by o-dasher** [comment]
imo, it should be completely fine to have keyboard support on osu!droid, and as someone who plays that game with a "kinda" competitive mindset, i don't think it gives much of an advantage, + you said that it's still a paid thing that should makes things unfair, 120hz+ phones are already there, they are way way expensive and gives way more than an advantage than any keyboard would bring for a game like osu!droid, still one could argue why bring another "unfairness" for the game with that, there isn't much of a reason not to when things like your screen size or tsr or hz or even other minor factors already make such of a bigger difference in a competitive scene.
I see it more as a opening for another ways to enjoy the game.

**Comment by N0tvich** [comment]
@o-dasher  you're right, playing with keyboard and mouse doesn't make much of a difference in competitive scenes, so casual gamers can enjoy osu! droid in a different way

**Comment by Beyley** [comment]
> 

Theres a difference between phone refresh rate and an external keyboard, screens can be overclocked to higher refresh rates
while you *have* to own multiple external things and plug them into your device to use a keyboard
i already stated why screen size doesnt matter
either way you can still read AR11 with 60hz

And lets talk about the physics of a keyboard vs glass when it comes to tactile feedback

When you and tapping on a keyboard, theres travel time and theres a consistence in feeling when you bottom out, which if you are skill enough to take advantage of that middle ground of bottoming out and not fully depressed, you can spam WAY faster
Along with that consistent traveltime + the bottoming out of keys, its a lot easier to alternate and get accuracy, as you have a constant feeling of changing resistance while your finger is moving, when with a touchscreen, you ONLY have that bottoming out, and its instant, meaning its a lot harder to adjust to alternating or get accuracy, as you dont have any tactile feedback

**Comment by Beyley** [comment]
This leads to keyboards having certain competitive advantages over a touchscreen player that *cant* be worked against
The main one being they can physically spam faster as theres pushback

**Comment by N0tvich** [comment]
F bro

**Comment by N0tvich** [comment]
because they left opsu! a good project

**Comment by Rian8337** [comment]
The main problem with adding keyboard and mouse support is handling mouse and keyboard events. This must be done in a way such that it supports both gameplay and replay, both with or without either of those hardwares. With the way things are structured as of now, this is *very* hard to do, and not worth the development cost considering most players play with touchscreen.

The game only recognizes 1 input type (which is touch). Changing it will require a rework to replay cursor movement and input handling. This adds another layer of complexity as we'd also need to decide what to do with touchscreen. Due to that, the easiest and most straightforward way I can think of to work around the problem is to map keyboard/mouse events to the touch such that the game picks it up as a touch event (this is reversed to what osu!framework does).

The main problem with the above approach is mapping mouse and keyboard press events to whatever position in the screen can make you accidentally press a note while playing. In my opinion, this is a very bad UX, making this approach not worth it. Trying to work around this also introduces another problem and (yet) more considerations for discussion.

**Comment by Beyley** [comment]
since there are competitive differences, youd have to mark scores that are done with mouse/kb and what if someone just has it plugged in and not in use? or they are playing touch and get a cool score but oops they accidentally bumped their wireless mouse half way through, itd add to the bad UX problems rian talked about

**Comment by N0tvich** [comment]
Thank you, the answer was that simple, it is somewhat unnecessary to work on that aspect or focus resources since there are very few players who play with keyboard and mouse

**Comment by spongebozz** [comment]
i wan't to request, can make a osu!droid slider similar to osu stable?
![IMG_20220802_213640](https://user-images.githubusercontent.com/107622751/182402343-4fa0298c-e4bc-4b0d-93af-e887951f9504.jpg)

**Comment by reco1I** [comment]
> i wan't to request, can make a osu!droid slider similar to osu stable?

be more specific

**Comment by Likver** [comment]
> > i wan't to request, can make a osu!droid slider similar to osu stable?
> 
> be more specific

he probably means the stable sliders style, with that degraded(?) line

**Comment by Beyley** [comment]
> > > i wan't to request, can make a osu!droid slider similar to osu stable?
> > 
> > be more specific
> 
> he probably means the stable sliders style, with that degraded(?) line

you somehow made it less specific

**Comment by Likver** [comment]
> > > > i wan't to request, can make a osu!droid slider similar to osu stable?
> > > 
> > > 
> > > be more specific
> > 
> > 
> > he probably means the stable sliders style, with that degraded(?) line
> 
> you somehow made it less specific

This 
![Screenshot_20220820-045804_cropped](https://user-images.githubusercontent.com/79934166/185726443-14385751-4577-4c6b-8fdc-b12bca5bef5f.png)

U know, in droid the slider body looks flat, he prob means this

**Comment by rust2** [comment]
> > [#11 (comment)](https://github.com/osudroid/osu-droid/issues/11#issuecomment-1013768574)
> > > Doesnt change that its kinda a bit overpowered on certain types of maps, and would be unfair to the other players, and "its cheap" doesnt mean that its still not a paid advantage
> > > Most of the players are very young, they likely dont have the money to buy it, it wouldnt be fair to them
> > 
> > 
> > Add a special mod for those, who plays with any peripheral like osu!lazer's "Touch Device" mod
> 
> just play osu!lazer instead

Yeah, their parents bought them good enough phone to run lazer
Also, is it so hard to implement that feature?

**Comment by reco1I** [comment]
> > > [#11 (comment)](https://github.com/osudroid/osu-droid/issues/11#issuecomment-1013768574)
> > > > Doesnt change that its kinda a bit overpowered on certain types of maps, and would be unfair to the other players, and "its cheap" doesnt mean that its still not a paid advantage
> > > > Most of the players are very young, they likely dont have the money to buy it, it wouldnt be fair to them
> > > 
> > > 
> > > Add a special mod for those, who plays with any peripheral like osu!lazer's "Touch Device" mod
> > 
> > just play osu!lazer instead
> 
> Yeah, their parents bought them good enough phone to run lazer
> Also, is it so hard to implement that feature? Like regular unranked mod

it is what it is, if you want to use keyboard play lazer.
As it said before it couldn't be implemented due to how works current input system.

**Comment by rust2** [comment]
> It is what it is, if you want to use keyboard then play osu!lazer. As it said before it couldn't be implemented due to how works current input system.

Ah, the matter was in implementation. Got it
(Didn't notice [this](https://github.com/osudroid/osu-droid/issues/11#issuecomment-1013994753) comment

**Comment by Enamiikurushiiu** [comment]
Add osu! Opening theme when open up osu!droid https://youtu.be/HuFQkoL-0NM?si=Rj16A7WVwTW7szyu

It may be useless, but it's cool when seeing an little detail on o!d

**Comment by mahmoud34abc** [comment]
Can we have OTG USB mouse & keyboard input? I'm not sure if thats against how the game should be played, but it would be cool to be able to play the game as if its just normal osu!. And i know this is a large thing to do 😅 I'd love to contribute to be honest but my exams arent really letting me

**Comment by Acivev** [comment]
I have opened a new discussion section called 'Feature Request' to provide a better overview.

**Comment by KrumaTTomeYT** [comment]
Add Taiko Game mode 🙏
