### ISSUE TITLE
button size

### ISSUE THREAD

**Issue by zGGxPROz** [osudroid/osu-droid#120]
I would like to ask you to change the size of the buttons because they are too big

**Comment by el-dasher** [comment]
???

**Comment by Rian8337** [comment]
Please outline your issue more clearly.

Which buttons are too big? Are you using a custom skin? Many buttons in song selection menu can be scaled using skins, perhaps try with default skin first and see if it meets your expectations.

**Comment by zGGxPROz** [comment]
the action buttons of the game what is with the numbers inside in my
opinion they are exaggeratedly immense

Em sáb, 1 de mai de 2021 13:46, Rian8337 ***@***.***>
escreveu:

**Comment by ammarasyad** [comment]
What buttons with numbers inside? Which one are you talking about?

**Comment by zGGxPROz** [comment]
I will explain better. I'm asking if the possibility of decreasing the size
of the hitcircle is just too big

Em sáb, 1 de mai de 2021 14:54, ammarasyad ***@***.***>
escreveu:

**Comment by Rian8337** [comment]
Changing hitcircle size can only be done with mods. There is no other way around this.

**Comment by Beyley** [comment]
> …

Hitcircle size was bumped up to make the game more playable, as on a tiny phone screen the normal CS size from stable would not translate well at all, making it smaller would impact gameplay and could be an unfair advantage on reading maps, just slap on HR if its really that much of an issue

**Comment by PayToUse** [comment]
For configuring the hitcircle size, use the force statistics mod
