### ISSUE TITLE
Music | BUG

### ISSUE THREAD

**Issue by AtapZ** [osudroid/osu-droid#123]
**When` you lost and quickly press the Back button, then the music continues to play**

**Comment by Rian8337** [comment]
Needs more detail. Which version of the game are you currently using?

**Comment by AtapZ** [comment]
When the final screen appears, I immediately press the Back button and END MUSIC continues playing. Have to re log in. 1.6.8

**Comment by Rian8337** [comment]
This has been fixed in the latest pre-release. Are you sure about this?

**Comment by AtapZ** [comment]
Yes, this happens rarely I would record a video, screen recording with sound my old Android not support

**Comment by Rian8337** [comment]
Looking back at this again, I can think of two possibilities to describe "END MUSIC"; either the music of the beatmap has not finished yet (which is intended), or the applause skin sound keeps playing (which should be fixed).

Closing as completed.
