### ISSUE TITLE
Beatmap proccesing

### ISSUE THREAD

**Issue by pixelguy126** [osudroid/osu-droid#127]
Now for some reason when i process too many beatmaps it crahes without forgetting the fact that it takes so long to process them each time two times .optimizating it or finding an alternate for the beamap proccesing would be good so that it goes faster and be optimized.

**Comment by Rian8337** [comment]
1. Were you able to isolate which beatmap causes the game to crash?
2. Which version of the game are you using?
3. Is there any error message that pops up before the game closes?

**Comment by tungggabc74** [comment]
> each

I think it can be solved by using "Clear all map data" in Beatmaps settings

**Comment by Rian8337** [comment]
A new beatmap processor has been implemented, hopefully this works better for your problem.
