### ISSUE TITLE
Better GitHub Description

### ISSUE THREAD

**Issue by rockedsocks** [osudroid/osu-droid#129]
So like, theres nothing in the GitHub description.

*This should be changed in order to give contributors and users a better idea of what this is at first glance, such as saying its an osu! client with extra features and such.*

**Comment by Acivev** [comment]
I have a readme on my branch
[GitHub Readme](https://github.com/Acivev/osu-droid/blob/readme/README.mdl)

**Comment by Rian8337** [comment]
With the README being updated already, I assume this is resolved.
