### ISSUE TITLE
SpinnerLock Issue/Bug

### ISSUE THREAD

**Issue by OfficialAz3** [osudroid/osu-droid#13]
Hello Osudroid devs.

I just want to say that there is a bug where Sliders & Circles won't respond when a Spinner is in the gameplay. Even if the SliderLock Option exists in settings, it still doesn't work.

I recorded my gameplay of a 2B map as an example for a bug, I wrote everything in the description to explain the bug I've been experiencing.

Same as implementing a SpinnerLock option or merging that request to SliderLock options to the settings.

Link here: https://youtu.be/6mTtHZH5LPM

**Comment by None1637** [comment]
I can't replicate this bug, so I don't know how to fix this bug
