### ISSUE TITLE
imported beatmaps wont show on game

### ISSUE THREAD

**Issue by Joshwelyt** [osudroid/osu-droid#135]
i imported a beatmap but when i open the game sure it shows imported but it wont show in the game itll just say no songs

**Comment by el-dasher** [comment]
I guess you need to be more specific than this.

**Comment by tungggabc74** [comment]
Uhh... You can try exporting the song with opsu and convert the exported music file to the Songs file of osu!droid

**Comment by Likver** [comment]
Are u sure u downloaded standard game mode beatmaps right?

**Comment by 5182008** [comment]
You sure it wasnt mania or taiko or osu!catch?

**Comment by Rian8337** [comment]
Should be fixed with the new beatmap processor.
