### ISSUE TITLE
Skinning, frames per second (fps) 

### ISSUE THREAD

**Issue by NimiPvPGamer** [osudroid/osu-droid#141]
Make unlimited frames for objects, skinning, like; scorebar-colour, play-skip, menu-back and etc.

**Comment by tungggabc74** [comment]
Yea, i hate 60 frame limit

**Comment by reco1I** [comment]
Why would you want more?

**Comment by Likver** [comment]
> Why would you want more?

for 60hz+ screens for example

**Comment by Rian8337** [comment]
Solved with #412.
