### ISSUE TITLE
NCPR bug

### ISSUE THREAD

**Issue by tungggabc74** [osudroid/osu-droid#142]
Ok, so when I pick NCPR and play this game, the app will crash immediately when i touch the screen. But when I pick DTPR instead of NCPR it didn't happen. My version is 1.6.8(122507)-github [Video for those who want to understand what's going on](https://youtu.be/WCk3lZM2LUo) Pls fix my favorite mode. (Sorry for my bad English)

**Comment by tungggabc74** [comment]
Wait, it also happens when you only enable Nightcore mod

**Comment by Rian8337** [comment]
Please try these options and see if they fix your problem:

1. Play with default skin.
2. Play using the latest pre-release build.
