### ISSUE TITLE
re updating the data base everytime 

### ISSUE THREAD

**Issue by pixelguy126** [osudroid/osu-droid#144]
so everytime i enter the game even without adding new beat maps the game updates the data base or Library. and after looking into the library code it seems like it never updates cuz the file is empty. idk how to fix that.

**Comment by Acivev** [comment]
im already working on the newer version of the library

**Comment by pixelguy126** [comment]
a

**Comment by kairusds** [comment]
Change your skin path from the settings.

**Comment by Rian8337** [comment]
Should be fixed in the next release.
