### ISSUE TITLE
Can't install the game maybe my phone is the problem 

### ISSUE THREAD

**Issue by philipxd27** [osudroid/osu-droid#145]
INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed reading assets/sfx/nightcore-clap.wav in java.util.jar.StrictJarFile@66362a1: META-INF/MANIFEST.MF has invalid digest for assets/sfx/nightcore-clap.wav in assets/sfx/nightcore-clap.wav

I try to install the pre-realest 2nd stage

**Comment by kairusds** [comment]
did you try installing a modified version of the game?
