### ISSUE TITLE
Random frame drop

### ISSUE THREAD

**Issue by timelessnesses** [osudroid/osu-droid#147]
So I have some ~~really~~ good phone that was good enough to not do random frame drops and while I having debug osu!droid someday random frame drop happen in random times.  
Hope fix it
I checked that
- skin is not problem
- latest release (pre release)
- ram is not issue
###### ~~ey unban me in discord server please :D~~

**Comment by Likver** [comment]
What options are u using?

**Comment by dumb-stuff** [comment]
uh
Android 10
Latest Beta Release

**Comment by kairusds** [comment]
> uh Android 10 Latest Beta Release
What specific game version is it? `Latest` is too broad.

**Comment by Nasthemikoy** [comment]
I have same problem too

**Comment by Beyley** [comment]
> I have same problem too
> 

congrats

**Comment by timelessnesses** [comment]
yeah it kind based on phones so I'm gonna close this
