### ISSUE TITLE
Working for 1.6.8 pre-release 3rd stage

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#158]
# Prepare stage  (now~2021.12.26)
prepare for new prerelease update, list all things we need to do before prerelease update , and finish them.

- [ ] #159

# Test stage  (2021.12.27- 2022.01.02)  
do not accept new feature update, only accept bug fix and translation.

# Update stage (2022.01.03-2022.01.09)
if all things works well, i will release a new prerelease version

**Comment by Beyley** [comment]
this issue should be closed, as prerelease 3 is already out, and the linked checklist is completed
