### ISSUE TITLE
Prepare stage todo list

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#159]
- [x] #160 
- [x] #161 
- [x] #162 
- [x] #167

**Comment by kairusds** [comment]
> * [x]  [Avatar download fails with new server #160](https://github.com/osudroid/osu-droid/issues/160)
> * [ ] [Unranked scores doesn't get saved when in online mode #167](https://github.com/osudroid/osu-droid/issues/167)
> * [x]  [Replay submission fails in new server #161](https://github.com/osudroid/osu-droid/issues/161)
> * [x]  [Background volume setting is not applied immediately after game start #162](https://github.com/osudroid/osu-droid/issues/162)
