### ISSUE TITLE
Skin folder reads skin assets

### ISSUE THREAD

**Issue by ZZdashX** [osudroid/osu-droid#164]
osudroid reads assets from Skin folder for some reason.

Setting my own skin as default skin:
![Screenshot_2021-12-23-23-07-41-04_846b44643ec609f507828878741e1f9a](https://user-images.githubusercontent.com/69755423/147258826-374bb18f-07ef-4eda-b35a-8f3ad237c6cd.jpg)

Skin set: default
![Screenshot_2021-12-23-23-12-17-19_41e4bcfddb1ad8126986d42329ac2750](https://user-images.githubusercontent.com/69755423/147259335-3a6ab525-b39b-4f76-b293-34fff7094ecb.jpg)

![Screenshot_2021-12-23-23-12-55-02_41e4bcfddb1ad8126986d42329ac2750](https://user-images.githubusercontent.com/69755423/147259359-f30bafd2-fa46-4f41-af17-e67bc68de980.jpg)

**Comment by Beyley** [comment]
This is intentional

**Comment by ZZdashX** [comment]
i mean, the game reads assets from the Skin folder which overwrites some default stuff

![Untitled122_20211223234245](https://user-images.githubusercontent.com/69755423/147262790-19c52f37-9d19-4246-992f-db38d2d92a44.png)

In this case, if your skin has a missing combobreak.wav element this will took over

**Comment by Beyley** [comment]
> i mean, the game reads assets from the Skin folder which overwrites some default stuff
> 
> ![Untitled122_20211223234245](https://user-images.githubusercontent.com/69755423/147262790-19c52f37-9d19-4246-992f-db38d2d92a44.png)
> 
> In this case, if your skin has a missing combobreak.wav element this will took over

yeah thats an intentional feature

**Comment by ZZdashX** [comment]
> > i mean, the game reads assets from the Skin folder which overwrites some default stuff
> > ![Untitled122_20211223234245](https://user-images.githubusercontent.com/69755423/147262790-19c52f37-9d19-4246-992f-db38d2d92a44.png)
> > In this case, if your skin has a missing combobreak.wav element this will took over

> yeah thats an intentional feature
No it's not
The purpose of this folder is to read skin folders, not skin elements w

**Comment by Beyley** [comment]
> > > i mean, the game reads assets from the Skin folder which overwrites some default stuff
> > > ![Untitled122_20211223234245](https://user-images.githubusercontent.com/69755423/147262790-19c52f37-9d19-4246-992f-db38d2d92a44.png)
> > > In this case, if your skin has a missing combobreak.wav element this will took over
> 
> > yeah thats an intentional feature
> > No it's not
> > The purpose of this folder is to read skin folders, not skin elements w

This feature carries back to pre 1.6.6(?) builds where there were no skin folders, rather a single one (its why the folder is called `Skin` not `Skins`)
It still pulls from the root `Skin` folder for backwards compat, im sure there are a lot of old players who sitll use the legacy skin scheme so chaning it is a terrible idea right now

**Comment by ammarasyad** [comment]
this is entirely intentional

**Comment by ZZdashX** [comment]
o

**Comment by Beyley** [comment]
since this is intentional, can someone close this issue?
