### ISSUE TITLE
[Ranking] Rank Small Circle mod which always display Unranked label in game

### ISSUE THREAD

**Issue by Xujiayao** [osudroid/osu-droid#168]
When Small Circle mod is enabled, the Unranked label is displayed in the latest version (debug).

Without Small Circle mod, it would be weird to play on a tablet, and that label is annoying as it is always displayed in game.

It is a good idea to set it to Ranked, or simply just provide an option for users to disable the display of Unranked label (Maybe Offline Mode Only).

For problem with circle size, see https://github.com/osudroid/osu-droid/issues/168#issuecomment-1002900554

Thanks!

**Comment by GIorp3179** [comment]
You can find a transparent png and rename it as play-unranked.png. Put it in whatever skin you're currently using and it'll make it transparent

**Comment by Xujiayao** [comment]
> You can find a transparent png and rename it as "play-unranked.png". Put it in whatever skin you're currently using and it'll make it transparent 

Good idea, but this is only a temporary solution. The problem of circle size adaptation when playing on the tablet still needs to be solved.

**Comment by Rian8337** [comment]
We're not looking into ranking new mods for the time being, sorry.

As for the circle size, it was changed in 1.6.7 to be that big. Playing harder maps in tablets before 1.6.7 were almost not viable due to how small the notes were. For reference, [here](https://youtu.be/X9z6A_VxQN4) is a video that compares circle size between 1.6.6 and 1.6.7.

**Comment by Xujiayao** [comment]
> We're not looking into ranking new mods for the time being, sorry.
> 
> As for the circle size, it was changed in 1.6.7 to be that big. Playing harder maps in tablets before 1.6.7 were almost not viable due to how small the notes were. For reference, [here](https://youtu.be/X9z6A_VxQN4) is a video that compares circle size between 1.6.6 and 1.6.7.

Oh okay, understandable. 😂

Well, I watched the video you provided. I compared that video with the screenshot of my tablet (10.8" 2560x1600), and you can see that the size of the circle is really too big without Small Circle mod!

I think it is necessary to make some adaptations to the current tablets.

![comparison](https://user-images.githubusercontent.com/58985541/147729401-470e9652-82a8-4986-be64-f970d9418fa9.png)

**Comment by Xujiayao** [comment]
> You can find a transparent png and rename it as "play-unranked.png". Put it in whatever skin you're currently using and it'll make it transparent

This is a great solution for someone like me who doesn't connect to osu!droid server for ranking (i.e. use Offline Mode).

@Rian8337 Hi! If there is a plan to rank Small Circle mod, or simply just provide an option for players to disable the display of Unranked label (maybe Offline Mode only), this issue can be kept open, otherwise it can be closed. Thx.

**Comment by Beyley** [comment]
> > You can find a transparent png and rename it as "play-unranked.png". Put it in whatever skin you're currently using and it'll make it transparent
> 
> This is a great solution for someone like me who doesn't connect to osu!droid server for ranking (i.e. use Offline Mode).
> 
> @Rian8337 Hi! If there is a plan to rank Small Circle mod, or simply just provide an option for players to disable the display of Unranked label (maybe Offline Mode only), this issue can be kept open, otherwise it can be closed. Thx.

as stated before, just skin it away if you don't want the text on screen, it's not a "temporary solution", it will last forever, and gameplay will not be changed on a tablet for fairness
