### ISSUE TITLE
osu!droid crashes when playing with Nightcore mod on certain maps

### ISSUE THREAD

**Issue by mshhlvxk** [osudroid/osu-droid#176]
### Issue description

- Expected result: Play normally with pitch change and speed + nightcore claps
- Actual result: Game crash

### Steps to reproduce the issue
1. Select Nightcore mod
2. Play any map (doesn't work on some maps)
It happened to me while playing tyDi ft. RUNAGROUND - Chase you down and the old osu! Tutorial

#### Additional details / Screenshot / Clip
- ...

### Versions
* Android version: latest
* Game version: latest

**Comment by Beyley** [comment]
could you attatch a crashdump?

**Comment by mshhlvxk** [comment]
The only message I got was "sorry, abnormal program will now exit".

**Comment by mshhlvxk** [comment]
Toast popup.

**Comment by Beyley** [comment]
> Toast popup.
> 

yes, can you post the crash logs

**Comment by mshhlvxk** [comment]
nvm its fixed here now
