### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [osudroid/osu-droid#177]
## Description
Could you please publish this app on F-Droid?

## Justification
F-Droid is an app store for FOSS apps. osu-droid is a great FOSS app. If this app can be published in F-Droid it can reach more FOSS fans.

**Comment by Beyley** [comment]
we are unable to push to any storefronts at the moment due to legal issues

**Comment by linsui** [comment]
Could you please elaborate?

**Comment by ammarasyad** [comment]
> Could you please elaborate?

several assets are made by peppy, so we do not have the rights to publish the game to any storefronts until a full replacement of the assets are done, which is not complete yet as of now

**Comment by linsui** [comment]
Got it, thanks!
