### ISSUE TITLE
Sometimes it says Sorry, abnormal program will now exit.

### ISSUE THREAD

**Issue by LexEzekiel2020** [osudroid/osu-droid#179]
### Everytime i change my game BGM

- Expected result: I thought it will freeze my game for 10 seconds - 
- Actual result: It will say "Sorry, abnormal program will now exit". 

### Steps to reproduce the issue
1. When you exit and enter settings repeatedly when your osudroid profile is loading. 

2. Or just mess up with your game by tapping on a beatmap difficulty fast. 

#### Additional details / Screenshot / Clip
-https://www.facebook.com/groups/1687004211558503/permalink/3104812256444351/?app=fbl
I submitted the screenshot in the osudroid Facebook page

### Versions
* Android version: Android 8.1.0
* Game version: 1.6.8 3rd Stage Pre-release

**Comment by j4cegh** [comment]
> Known issue. No fix as of now because the cause is random and crashlogs are inconclusive as it does not point to the source, rather a generic/vague error.
True.
The cause is hard to determine and there just might not be one. Tough...
