### ISSUE TITLE
No login

### ISSUE THREAD

**Issue by mrmeow58** [osudroid/osu-droid#180]
### Issue description
I was trying to play to rank up a little then it just said unknown server error
- Expected result: What were you expecting to happen? I log in
- Actual result: What actually happened?
I didn't log in
### Steps to reproduce the issue
1. Log in
2. Error
- ...

### Versions
* Android version: 11
* Game version:1.6.8 pre 3

**Comment by Rian8337** [comment]
The servers are undergoing maintenance right now. Please wait until it's finished.
