### ISSUE TITLE
Instaretry after save replay crash

### ISSUE THREAD

**Issue by unclem2** [osudroid/osu-droid#184]
### Issue description

- Expected result: Crash of the application with the possible preservation of the errorlog
- Actual result: Crash of the game without preservation of errorlog

### Steps to reproduce the issue
1. Fail
2. Tap on the save replay button and instatly tap retry button

#### Additional details / Screenshot / Clip
- https://youtu.be/IkFKjkmrjrw

### Versions
* Android version: 10.QP1A.190711.020
* Game version: 1.6.8 3rd prerelease(220109)

### Crashdump, backtrace or other files
Not created during crash

**Comment by Likver** [comment]
Not needed to instantly restart the beatmap, but the save replay button and then the replay button (at least for me)
