### ISSUE TITLE
osu!droid Map Editor

### ISSUE THREAD

**Issue by LexEzekiel2020** [osudroid/osu-droid#186]
osu!droid Map Editor
## Description
If you want to Make or Edit a Beatmap, then a Map Editor Will Be Nice.

 Why go for a map editor? Well the thing is i really wanted to make a Beatmap, but i don't have a pc. And why i wanted a map editor because you can make any Beatmap that you want. If you don't find this idea helpful or useless, just throw this idea in the trash. But if you do find this idea helpful and add this feature to the game. I will be happy. (by the way this is a feature request, just correct me if i sent this on the bug report issues) 
## Justification
I don't know what to say here. Pls help

## Alternative methods
Same thing i said on the Justification thing

**Comment by j4cegh** [comment]
This is a very broad and difficult suggestion to implement. I mean, yeah, sure. It's going to be incredibly nice to add such a thing, but will it be easy? Nope. Also there's a need of acceptance for this. The team needs to accept it before anything happens.

**Comment by Beyley** [comment]
> osu!droid Map Editor
> ## Description
> If you want to Make or Edit a Beatmap, then a Map Editor Will Be Nice.
> 
> Why go for a map editor? Well the thing is i really wanted to make a Beatmap, but i don't have a pc. And why i wanted a map editor because you can make any Beatmap that you want. If you don't find this idea helpful or useless, just throw this idea in the trash. But if you do find this idea helpful and add this feature to the game. I will be happy. (by the way this is a feature request, just correct me if i sent this on the bug report issues)
> ## Justification
> I don't know what to say here. Pls help
> 
> ## Alternative methods
> Same thing i said on the Justification thing

this already exists https://github.com/inix1257/osuEdit

**Comment by j4cegh** [comment]
> > osu!droid Map Editor
> > ## Description
> > If you want to Make or Edit a Beatmap, then a Map Editor Will Be Nice.
> > Why go for a map editor? Well the thing is i really wanted to make a Beatmap, but i don't have a pc. And why i wanted a map editor because you can make any Beatmap that you want. If you don't find this idea helpful or useless, just throw this idea in the trash. But if you do find this idea helpful and add this feature to the game. I will be happy. (by the way this is a feature request, just correct me if i sent this on the bug report issues)
> > ## Justification
> > I don't know what to say here. Pls help
> > ## Alternative methods
> > Same thing i said on the Justification thing
> 
> this already exists https://github.com/inix1257/osuEdit

Oh, awesome!

**Comment by LexEzekiel2020** [comment]
> > osu!droid Map Editor
> > ## Description
> > If you want to Make or Edit a Beatmap, then a Map Editor Will Be Nice.
> > Why go for a map editor? Well the thing is i really wanted to make a Beatmap, but i don't have a pc. And why i wanted a map editor because you can make any Beatmap that you want. If you don't find this idea helpful or useless, just throw this idea in the trash. But if you do find this idea helpful and add this feature to the game. I will be happy. (by the way this is a feature request, just correct me if i sent this on the bug report issues)
> > ## Justification
> > I don't know what to say here. Pls help
> > ## Alternative methods
> > Same thing i said on the Justification thing
> 
> this already exists https://github.com/inix1257/osuEdit

But that doesn't work anymore. Luscent, the creator of osuEdit didn't made any changes, you can't save your custom made map even though you saved it. It will not show up on osudroid because the map that you made on osuEdit is corrupted and cannot be played. Although if you are a master of java coding you can make that app work

**Comment by Beyley** [comment]
> > > osu!droid Map Editor
> > > ## Description
> > > If you want to Make or Edit a Beatmap, then a Map Editor Will Be Nice.
> > > Why go for a map editor? Well the thing is i really wanted to make a Beatmap, but i don't have a pc. And why i wanted a map editor because you can make any Beatmap that you want. If you don't find this idea helpful or useless, just throw this idea in the trash. But if you do find this idea helpful and add this feature to the game. I will be happy. (by the way this is a feature request, just correct me if i sent this on the bug report issues)
> > > ## Justification
> > > I don't know what to say here. Pls help
> > > ## Alternative methods
> > > Same thing i said on the Justification thing
> > 
> > 
> > this already exists https://github.com/inix1257/osuEdit
> 
> But that doesn't work anymore. Luscent, the creator of osuEdit didn't made any changes, you can't save your custom made map even though you saved it. It will not show up on osudroid because the map that you made on osuEdit is corrupted and cannot be played. Although if you are a master of java coding you can make that app work

its probably just slightly broken, i think you are overestimating the effort required
also you could just wait until osu!lazer's editor is in better shape

**Comment by SheeshDough** [comment]
you can't edit map without computer osu!
