### ISSUE TITLE
Auto Disable Hit Burst

### ISSUE THREAD

**Issue by NotCrafted** [osudroid/osu-droid#189]
## The game could put the said Burst Effect Toggle on menu/mods/settings

**Comment by Acivev** [comment]
Fixed issue
4934837c97d8be082563aadfbfa3d228930b79af

**Comment by NotCrafted** [comment]
Uhh... How can I download it 💀

**Comment by Rian8337** [comment]
You need to compile the apk by yourself, however the compiled apk will not be able to connect to the server.

If you want to be able to connect to the server, you need to wait for the next release (either 4th pre-release or the final 1.6.8 version).
