### ISSUE TITLE
Cursor get freezes

### ISSUE THREAD

**Issue by crischutu07** [osudroid/osu-droid#190]
### Issue description

- Expected result: don't want get an cursor freeze
- Actual result: When you clicking and wipe the cursor around, the wipe cursor will freeze

### Steps to reproduce the issue
1. open osudroid
2. choose any map (ex: Ata - Eutopia)
3. stream a map (result: cursor freezes)

#### Additional details / Screenshot / Clip
- https://youtu.be/htm4QhgF-Yw (example of Stream map)
- ![Screenshot_2022-05-31-18-05-51-71_41e4bcfddb1ad8126986d42329ac2750](https://user-images.githubusercontent.com/81855366/171162241-5631a7fd-ecc9-4428-9dd0-af73a8fbd8e9.jpg) (some cursor freezes)

### Versions
* Android version: 11
* Game version: 1.6.8 3rd Stage Pre-release

**Comment by crischutu07** [comment]
In the video

**Comment by Rian8337** [comment]
Have you turned off gestures like "slide three fingers to take screenshot"?

**Comment by crischutu07** [comment]
> Have you turned off gestures like "slide three fingers to take screenshot"?

I don't know where is that optio. .-.

**Comment by Rian8337** [comment]
The location of the option varies depending on the ROM that you use. Feel free to search on the internet.

**Comment by crischutu07** [comment]
> The location of the option varies depending on the ROM that you use. Feel free to search on the internet.

Oh i see

**Comment by Rian8337** [comment]
Closing this as there is no response from the OP so far, assuming it is resolved
