### ISSUE TITLE
Add Discord Rich Presence 

### ISSUE THREAD

**Issue by crischutu07** [osudroid/osu-droid#193]
## Description
Hello osudroid Developer, please add Discord Rich Presence is a good idea to add.

## Justification
Using Discord Rich Presence is the best idea for who have Discord and other people can know your status like: You're current playing a map and Mods are you playing

## Alternative methods
Discord have a link helping Developer can add Discord Rich Presence so you can add it easily (I think so) in [here](https://discord.com/rich-presence)

**Comment by Rian8337** [comment]
Discord Rich Presence is not supported in mobile devices.

The only exception are some Samsung phones, which has integration with Discord in their Game Hub application.

**Comment by crischutu07** [comment]
> Discord Rich Presence is not supported in mobile devices.
> 
> The only exception are some Samsung phones, which has integration with Discord in their Game Hub application.

Some of app may support Discord Rich Presence of any Android Phone, take a example like Spotify

**Comment by Rian8337** [comment]
That's because they work together.

To add Discord Rich Presence to an application, you need to use Discord's GameSDK, which is not supported in mobile platforms.
