### ISSUE TITLE
Leaderboard is not showing in any map

### ISSUE THREAD

**Issue by crischutu07** [osudroid/osu-droid#200]
### Issue description

- Expected result: Make the leaderboard map showing again like any version 
- Actual result: Leaderboard is not showing after the "Couldn't submit score" error in the profile menu (you can see the error on the corner of the menu)

### Steps to reproduce the issue
1. open osu!droid
2. Choose any map (Example: use any popular map like **Red Like Rose**)
3. Press the Home button in the corner (not the android home button)
4. A empty leaderboard showing up

#### Additional details / Screenshot / Clip
- 
![Screenshot_2022-07-05-14-45-41-56_41e4bcfddb1ad8126986d42329ac2750](https://user-images.githubusercontent.com/81855366/177277618-ea7b56e3-4429-4509-af48-dea769f3e33e.jpg)

### Versions
* Android version: 11 
* Game version: 1.6.8 Pre-release 3rd Stage

**Comment by Rian8337** [comment]
Thanks for your report. This is a known issue and is currently being worked on the server-side.

**Comment by crischutu07** [comment]
> Thanks for your report. This is a known issue and is currently being worked on the server-side of things.

Thanks
