### ISSUE TITLE
make the limit combo of any beatmap

### ISSUE THREAD

**Issue by crischutu07** [osudroid/osu-droid#201]
## Description
I'd requesting limit combo of the beatmap, if you dont know what am I saying, example: if the beatmap has 1203x combo and you played that beatmap over 1304x, the game will not summit that score because you go through the limit of that combo, also if someone is making +2 higher than the beatmap FC combo, the game will only summit 1203x😉

## Justification
To know why this is good because some hacker making through the limit of beatmap combo making hacker/cheater got top 1 leaderboard of that beatmap 

## Alternative methods
I don't know💀

**Comment by Rian8337** [comment]
Thanks for the suggestion, but this is not possible as the server cannot exactly pinpoint the maximum combo of a beatmap.
