### ISSUE TITLE
I can't play osu droid

### ISSUE THREAD

**Issue by BusinessBo** [osudroid/osu-droid#205]
### Issue description

- Expected result: What were you expecting to happen? I just want to play osu droid
- Actual result: What actually happened? I can't play osu droid

### Steps to reproduce the issue
1. ...
2. ...

#### Additional details / Screenshot / Clip
![Screenshot_20220903-113632](https://user-images.githubusercontent.com/83387636/188254487-e76a1e0e-5303-4df4-a6ba-9673e6fdbd96.png)

- ...

### Versions
* Android version:android 11
* Game version:1.6.8

**Comment by Beyley** [comment]
do what it says

**Comment by BusinessBo** [comment]
> 

Idk how to do it

**Comment by reco1I** [comment]
dumbest issue ever

**Comment by Beyley** [comment]
smartest osu!droid player

**Comment by SheeshDough** [comment]
turn off auto click or anything

**Comment by Beyley** [comment]
> turn off auto click or anything 

it's already closed
