### ISSUE TITLE
Make PF Mod playable with Relax and Autopilot 

### ISSUE THREAD

**Issue by crischutu07** [osudroid/osu-droid#207]
## Description
I want Perfect Mod (PF) Playable on Relax (RX) and Autopilot (AP)

## Justification
Perfect Mod (PF) is the SS mod, your goal is SS entire map, this could be useful for training like:
Aiming -> Relax, Finger Control -> Autopilot 

## Alternative methods
I don't know

**Comment by SheeshDough** [comment]
lol
