### ISSUE TITLE
Great Update

### ISSUE THREAD

**Issue by SheeshDough** [osudroid/osu-droid#209]
Cooperate with Opsu! Developer

I think is will make game better, because Opsu! has some features like PC Osu!
and Opsu! use Java code

Features:
Circle Mouse ![20220921_122423.jpg](https://user-images.githubusercontent.com/113880752/191421176-342cab53-a7bf-4bdb-be42-a3128c701c8e.jpg)

Opsu! Settings(like osu!)
![Screenshot_20220921-124532_opsu!.jpg](https://user-images.githubusercontent.com/113880752/191424027-973a3259-608d-41e5-9b67-87e8789f611a.jpg)

Opsu! on PlayStore: 
[]()https://play.google.com/store/apps/details?id=fluddokt.opsu.android

Opsu! Github: []()https://github.com/itdelatrisu/opsu

if cannot, pls add the circle and settings like it ![20220921_122423.jpg](https://user-images.githubusercontent.com/113880752/191424667-377eef06-1a46-4c0e-9218-d1bdae321b1d.jpg)![Screenshot_20220921-124532_opsu!.jpg](https://user-images.githubusercontent.com/113880752/191424675-569899d1-72e2-43f0-835b-66d530e444ca.jpg)

**Comment by Beyley** [comment]
licenses are incompatible, we cannot use opsu! source code

**Comment by SheeshDough** [comment]
> licenses are incompatible, we cannot use opsu! source code

if cannot pls add circle mouse ![20220921_122423.jpg](https://user-images.githubusercontent.com/113880752/191424916-4ee6f723-0e0d-48a3-8efd-d819bf3b0f57.jpg)

**Comment by TheParaTiger** [comment]
I'm not a Developer

But i think a Circle Mouse isn't Useful on osu!droid because Opsu! Was also optimized to be used on PC but you mainly only use touch on the Smartphone since osu!droid isn't supposed to be played with Mouse and Keyboard as far as i understand xD

**Comment by Likver** [comment]
U can alr use the cursor, just go to the game options > Graphics > Enable cursor (iirc the option was named something like that) and u will see the cursor while u play

**Comment by reco1I** [comment]
If you mean cursor in menus its doable but what's the point of that?

**Comment by SheeshDough** [comment]
> U can alr use the cursor, just go to the game options > Graphics > Enable cursor (iirc the option was named something like that) and u will see the cursor while u play

Thks too much

**Comment by Likver** [comment]
np

**Comment by SavainB** [comment]
can i work on this ?

**Comment by Beyley** [comment]
> can i work on this ?

we will not accept any code that is copied from opsu! without a written signature from all opsu! contributors relicensing the code to be compatible with osu!droid
