### ISSUE TITLE
To work on this project

### ISSUE THREAD

**Issue by rust2** [osudroid/osu-droid#213]
To work on this project in android studio, do I need to have only SDK level 21 installed?

on the [site](osudroid.moe), I see
> Use any Android device with version 2.3 or higher to play games.

But in the MiXplorer, I see:
> Target level: 9.+ (Q, API 29)
Minimum level: 5.0 (L, API21)

**Comment by rust2** [comment]
on the [site](osudroid.moe), I see
> Use any Android device with version 2.3 or higher to play games.

But in the MiXplorer, I see:
> Target level: 9.+ (Q, API 29)
Minimum level: 5.0 (L, API21)

**Comment by reco1I** [comment]
Please don't open an issue to ask something, you can ask whatever you want in the Discord development server.

The SDK it's necessary. You're probably referring to Android source code which is not necessary to code in this project.

**Comment by rust2** [comment]
sorry
