### ISSUE TITLE
i cant adjust the offset of the music correctly

### ISSUE THREAD

**Issue by mopeaki** [osudroid/osu-droid#216]
the music offset adjustment range of the current version is between -100~+100ms, but my custom setting is +185ms, this prevents me from playing comfortably.
fix it, plz
![593289725-895953220](https://user-images.githubusercontent.com/70810788/211214077-f3bcd6b1-2077-414c-b5d0-7b80f1534bd8.jpg)
![5932897251585284825](https://user-images.githubusercontent.com/70810788/211214078-6d094821-4077-49e1-9bb5-5ae9ef925068.jpg)

**Comment by Likver** [comment]
iirc it will be customizable again in next verion/versions
