### ISSUE TITLE
Mp4 background bug

### ISSUE THREAD

**Issue by TheBestXann** [osudroid/osu-droid#220]
mp4 background can't detect by osu! driod 

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

#### Additional details / Screenshot / Clip
- ...

### Versions
* Android version:13
* Game version:1.6.7

**Comment by reco1I** [comment]
Video background are not supported.

**Comment by Rian8337** [comment]
As mentioned. Unsure if this will be supported in the future.
