### ISSUE TITLE
Multi Touch bug on osu!droid

### ISSUE THREAD

**Issue by joseph23pronton** [osudroid/osu-droid#24]
My phone can support 10 simultaneously touch without problem but here at osu!droid it can only register 1 touch and im playing bangdream so multi touch is supported.
Android OS: EMUI 10.1(ANDROID 10)
PHONE: Huawei Y6P 2020 4Gb Ram

**Comment by EdrowsLuo** [comment]
not a game bug, your system intercept touch event, you should turn off screen gesture.
