### ISSUE TITLE
Crashing when clicking/tapping any beatmap

### ISSUE THREAD

**Issue by MilkMai** [osudroid/osu-droid#256]
### Issue description

- Expected result: select beatmap and show all its difficulties and play the map

- Actual result: game error message "sorry  abnormal program will exit now" then game crash

### Steps to reproduce the issue
1. Select any beatmap 

#### Additional details / Screenshot / Clip
- ...

### Versions
* Android version: 12, 
* Game version:1.6.8 230704-release

### Crashdump, backtrace or other files
> ![errorlog.txt](https://github.com/osudroid/osu-droid/files/11991322/errorlog.txt)

**Comment by reco1I** [comment]
Try changing skin

**Comment by SorryLemon** [comment]
> Try changing skin

That fixed it I guess it was just a problem with the skin
