### ISSUE TITLE
beatmaps don't load

### ISSUE THREAD

**Issue by zenners1** [osudroid/osu-droid#260]
When I download a beatmap and put it in the songs file the game doesn't load it, I check the songs dictionary and change it because it was set to sdcard instead of the main storage but it still didn't work, please give me a solution if possible or fix the bug

**Comment by Rian8337** [comment]
`/sdcard` points to your internal storage in most cases.

Additionally, please link the beatmap that you tried to import.

**Comment by zenners1** [comment]
> `/sdcard` points to your internal storage in most cases.
> 
> Additionally, please link the beatmap that you tried to import.

heree https://api.chimu.moe/v1/download/1867776?n=1

**Comment by Rian8337** [comment]
Apologies for the delay, I only had time to come back to this issue.

You are not importing an osu!standard beatmap. Please only download beatmaps which have the following icon:
![image](https://github.com/osudroid/osu-droid/assets/52914632/7e807b4c-4270-4081-a178-0ab2a0fd1766)

**Comment by zenners1** [comment]
ye i just know about that a few days ago , i didn't play osu for quite a long time so um yeahh i forgot gamemodes exist anyways i apologize for wasting your time :cOn 8/12/23, 11:05 PM Rian ***@***.***> wrote:

   
  Apologies for the delay, I only had time to come back to this issue. 
  You are not importing an osu!standard beatmap. Please only download beatmaps which have the following icon:
