### ISSUE TITLE
The skin.json file locks the color of hitcircles.

### ISSUE THREAD

**Issue by LerD7bio** [osudroid/osu-droid#261]
### Issue description

- Expected result: Each beatmap has its own combo colours that change the hitcircles color, and these are expected to change when playing different beatmaps.

- Actual result: The colors of the hitcircles are always the same as the default in the skin.json file no matter what beatmap you play.

### Steps to reproduce the issue
1. Open the game with a new skin.
2. Wait for the game to convert the skin.ini file to skin.json.

#### Additional details / Screenshot / Clip
- If you play version 1.6.7 with a skin that has the skin.json file, the problem will still be there, but if you delete that file and leave just the skin.ini the error will be fixed.

### Versions
* Android version:
* Game version: 1.6.8

**Comment by reco1I** [comment]
This is not a bug. The `skin.json` may have the option to override colors enabled. 

Play with another skin.

**Comment by LerD7bio** [comment]
> This is not a bug. The `skin.json` may have the option to override colors enabled.
> 
> Play with another skin.

oh, that was the problem.  

I already edited that option in the json files and now all my skins work fine. 

 Thank you.
