### ISSUE TITLE
stuck at loading skin... 40%

### ISSUE THREAD

**Issue by PensiFir** [osudroid/osu-droid#271]
install apk, enter game and stuck at 40% loading skin... . All permissions granted

#### Additional details / Screenshot / Clip
![image](https://github.com/osudroid/osu-droid/assets/62414660/787d348c-7ab1-4207-a881-d89d96488a1d)

### Versions
* Android version: 13
* Game version: v1.7.0-230821-release

**Comment by Rian8337** [comment]
Can you zip the content of your skin folder and attach it here?

**Comment by PensiFir** [comment]
> Can you zip the content of your skin folder and attach it here?

I don't use skin

**Comment by Rian8337** [comment]
Ok...

Multiple players have reported the same problem, so a hotfix will come. Please wait.

**Comment by Rian8337** [comment]
To add on, did you manage to get logs from this crash?

**Comment by PensiFir** [comment]
where can i find logs, i don't see any txt file in the osu!droid folder

**Comment by Rian8337** [comment]
So it was deleted, ok. Never mind, then.

**Comment by Rian8337** [comment]
As an update, we have identified the problem and are now working on the fix.
