### ISSUE TITLE
Illegal Action Detected 211 when using the button in the S Pen

### ISSUE THREAD

**Issue by timelessnesses** [osudroid/osu-droid#280]
### Issue description

- Expected result: Nothing.
- Actual result: Crash

### Steps to reproduce the issue
1. Open osu!droid
2. Click the button on the S Pen
3. Crash

#### Additional details / Screenshot / Clip
- The `AndEngine` seems to raise an error when S Pen button is clicked because it actually doesn't recognize the S Pen as an action.

### Versions
* Android version: 13
* Game version: 1.7.0

### Crashdump, backtrace or other files
https://pastebin.com/uUnwrBwd

**Comment by ammarasyad** [comment]
Doesn't happen on my end. Cannot reproduce the issue. Got any video clips? What's your phone?

**Comment by timelessnesses** [comment]
> Doesn't happen on my end. Cannot reproduce the issue. Got any video clips? What's your phone?

The tablet is Samsung S6 Lite and here's the [video](https://youtube.com/shorts/Tp_J1n6vUW0?si=ysmDOiPmnEq7WUQi) (i actually don't know why it uploaded it as short)

**Comment by ammarasyad** [comment]
> > Doesn't happen on my end. Cannot reproduce the issue. Got any video clips? What's your phone?
> 
> The tablet is Samsung S6 Lite and here's the [video](https://youtube.com/shorts/Tp_J1n6vUW0?si=ysmDOiPmnEq7WUQi) (i actually don't know why it uploaded it as short)

Please be more accurate with your report next time. The bug happens *if you tap the S-Pen with the button pressed*, not just with the S-Pen button press.

I can confirm this bug on my phone now with this added information. Thanks for the report.
