### ISSUE TITLE
 Make sure pull request #26 works well

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#29]
#26 : make sure this pull request works well.

**Comment by EdrowsLuo** [comment]
#32 Any change to song library should increse the library version number

**Comment by None1637** [comment]
it 's no change in song library, only add longer string string in mod column. I don't know whether to change the library version number or not,  under the circumstances.

**Comment by EdrowsLuo** [comment]
> it 's no change in song library, only add longer string string in mod column. I don't know whether to change the library version number or not, under the circumstances.

you recalculate star, which is stored in song library.

**Comment by Rian8337** [comment]
Stacked sliders (sliderheads) appears to be rendered incorrectly with precalculate slider path on.

Tested on https://osu.ppy.sh/beatmapsets/28751#osu/116128, should be more noticeable in other beatmaps that have a lot of stacked notes as well.

**Comment by None1637** [comment]
> 
> 
> Stacked sliders (sliderheads) appear to be rendered incorrectly with precalculate slider path on.
> 
> Tested on https://osu.ppy.sh/beatmapsets/28751#osu/116128, should be noticeable in other beatmaps that have long stacked notes as well.

Fixed in pull request #35

**Comment by Rian8337** [comment]
Is it intentional that force AR and speed modify modifiers are not stored in replays and only in score database file?

**Comment by None1637** [comment]
> 
> 
> Is it intentional that force AR and speed modify modifiers are not stored in replays? Apparently they are only stored in score database file.

Not intentional, but when I try to stored them in replays, new replays will can't be read by old version osu!droid(before this change, some replay can be read by old version). Shall I store them in replay?

**Comment by EdrowsLuo** [comment]
> > Is it intentional that force AR and speed modify modifiers are not stored in replays? Apparently they are only stored in score database file.
> 
> Not intentional, but when I try to stored them in replays, new replays will can't be read by old version osu!droid(before this change, some replay can be read by old version). Shall I store them in replay?

you should discuss this in #37 , and the problem you said can be fixed by judge replay file version.
