### ISSUE TITLE
Input Delay option gone?

### ISSUE THREAD

**Issue by SweetIceLolly** [osudroid/osu-droid#290]
### Issue description
The Input Delay option in the advanced option menu is gone, and seems it's always on - which makes my gameplay very uncomfortable.

- Expected result: Have the input delay option
- Actual result: no input delay option

### Steps to reproduce the issue
1. go to options -> advanced

#### Additional details / Screenshot / Clip
- ...

### Versions
* Android version: 12
* Game version:1.7.1 (230923)

**Comment by reco1I** [comment]
This option was removed because it's useless nowadays. Already said in the change log.

**Comment by SweetIceLolly** [comment]
Thanks for letting me know
