### ISSUE TITLE
Load beatmap not showing

### ISSUE THREAD

**Issue by CSharps-Tech** [osudroid/osu-droid#299]
### Issue description
I download 6 beatmap and "Archive successful, 0 beatmaps loaded"(VN: Lưu trữ thành công, Đã tải 0 beatmap)
- Expected result: What were you expecting to happen?
I only download chimu.moe beatmap and Give beatmap(s) to /Song/
- Actual result: What actually happened?
yes
### Steps to reproduce the issue
1. No beatmap
2. Loaded and 0 beatmap

#### Additional details / Screenshot / Clip
- sorry, I not be screenshot it

### Versions
* Android version: Android 11
* Game version: latest

### Crashdump, backtrace or other files

```
No files found
```

**Comment by reco1I** [comment]
Have you enabled the option to scan downloads folder?
