### ISSUE TITLE
Make precise mod ranked

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#30]
Precise mod is ready to be ranked, there are still some thing to do:

- [x]  determine score multiplier  (I think x1.05 is fine)

- [x]  client side coding

- [x]  server side coding

**Comment by OsuNoobForever** [comment]
Is it necessary to add precise into the ranked mods? I'm just wondering if it's going to be used from players? These are just my thoughts so please don't get mad.

**Comment by Rian8337** [comment]
Not sure if this is already in TO-DO list, but you should prevent old clients from logging in (pre-1.6.8) after making this mod ranked (considering 1.6.6 and below doesn't have Precise mod, 1.6.7 does but it will mark the mod as unranked).
