### ISSUE TITLE
Invisible slider on the sun the moon the stars

### ISSUE THREAD

**Issue by Lowertricker** [osudroid/osu-droid#363]
### Issue description

- Expected result:fc the sun the moon the stars
- Actual result:invisible slider which causes slider break on 5400+ combo

### Steps to reproduce the issue
1. play the sun the moon the stars and wait until you got 5400+ combo

#### Additional details / Screenshot / Clip
- ...

### Versions
* Android version:13
* Game version:1.7.2-p4

**Comment by Rian8337** [comment]
This is because the slider's path is computed on fly. You can enable the pre-calculate slider path setting to fix this. 

It does make me wonder whether this setting should be enabled by default...
