### ISSUE TITLE
some of text invisible

### ISSUE THREAD

**Issue by Lowertricker** [osudroid/osu-droid#364]
### Issue description

- Expected result:Pausing the game due to call
- Actual result:some of letters in text are invisible but when i type its not

### Steps to reproduce the issue
1. pause and leave osu droid
2. pause and turn off device(rare)

#### Additional details / Screenshot / Clip

- ...

### Versions
* Android version:1.7.2-p4
* Game version:

**Comment by Reco1I** [comment]
This is a game engine bug, just minimize and reopen the game you'll get it fixed.
