### ISSUE TITLE
Error en multiplayer

### ISSUE THREAD

**Issue by ballenaloi** [osudroid/osu-droid#368]
Los otros jugadores No pueden descargar los beatmaps del host de la partida en multijugador
![Screenshot_20240709-114256_osu!droid](https://github.com/osudroid/osu-droid/assets/77940057/86145a51-7fe9-451d-bc7c-4f2996361d56)
![Screenshot_20240709-114256_osu!droid](https://github.com/osudroid/osu-droid/assets/77940057/de4cfb12-494e-4e7b-9d43-d2673dfc2e1e)

**Comment by Rian8337** [comment]
This has been resolved server-side.
