### ISSUE TITLE
Still bug lol

### ISSUE THREAD

**Issue by ballenaloi** [osudroid/osu-droid#369]
El problema persiste, esta vez no deja descargar beatmaps que antes si se podian, por favor ayuda :'(
![Screenshot_20240712-103654_osu!droid](https://github.com/user-attachments/assets/da7d9f23-7125-4366-b686-91bc288fdb9f)
![Screenshot_20240711-234642_osu!droid](https://github.com/user-attachments/assets/face9b67-6449-4572-b9ac-cc16d036918c)

**Comment by Rian8337** [comment]
Please don't open new issues on the same problem (comment on the previous issue). Additionally, please use English.

Either way, a migration process for droid performance points was happening in the server, which caused this problem. Please try again.

**Comment by Reco1I** [comment]
> No abras nuevos incidentes para el mismo problema (comentá en el incidente que ya creaste). Además tratá de escribir en Ingles.
> 
> El servidor está atravesando un proceso de migración que probablemente esté causando el problema.

Personalmente voy agregar que no todos los mapas están disponibles para descargar desde el servidor.

**Comment by ballenaloi** [comment]
very good bro, but for next time, it is important to put the problem and
the solution, the vast majority of osu!droid players were not aware of what
the hell was happening on the servers, now that the matter has been
clarified, I appreciate your time. I hope the problem is resolved soon.
thank you.
Also to clarify something, if you know English you should learn Spanish
too, u mumbling 1d1o7.
