### ISSUE TITLE
Force AR and speed modify modifiers should stored in replays

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#37]
Is it intentional that force AR and speed modify modifiers are not stored in replays? Apparently they are only stored in score database file.

_Originally posted by @Rian8337 in https://github.com/osudroid/osu-droid/issues/29#issuecomment-704652710_

**Comment by Rian8337** [comment]
> Not intentional, but when I try to stored them in replays, new replays will can't be read by old version osu!droid(before this change, some replay can be read by old version). Shall I store them in replay?
@None1637 yes, you should. Edrows has told you in #29 about how to solve that issue. Additionally, if you intend to make this ranked in the future, storing them in replays are required.

**Comment by None1637** [comment]
> 
> 
> > Not intentional, but when I try to stored them in replays, new replays will can't be read by old version osu!droid(before this change, some replay can be read by old version). Shall I store them in replay?
> 
> @None1637 yes, you should. Edrows has told you in #29 about how to solve that issue. Additionally, if you intend to make this ranked in the future, storing them in replays are required.

That issue(If I stored them in replays, old version can't read new version replay) can't be solve. But I will store them in replay at next PR

**Comment by EdrowsLuo** [comment]
Solved in #38
