### ISSUE TITLE
Does the offset option set the map/song offset?

### ISSUE THREAD

**Issue by StringManolo** [osudroid/osu-droid#378]
I'm not sure if it's working or not. I believe the song/map are not moving at all. 

I have no problem to find offset at PC version (even when running it in Android) for no headsets, headsets, bluethoot speakers, etc. Same using OPSU.

In osu!droid i'm totally unable to find the right offset or get close at all. Even when i know what exactly beat match with what exact circle at start of a song. I been moving around from -500 to +500 in jumps of 50 and i can't notice any changes. Maybe it's implemented wrong and is changing the hitsound offsets instead of the map/song offset itself? Cuz i don't use hitsounds, i prefer using the tap/keyboard sounds itself.

Also you probably want to extend the offset range. Cuz if you use for example bluethoot speakers, is not weird at all to have a 600+ ms delay on an smartphone, so you have to set -600ms+ as offset.

PD: I think it's moving but it's inversed?

**Comment by Rian8337** [comment]
Yes, the offset is inversed. I do agree that it's unintuitive to the user - positive offset should indicate that objects appear later.
