### ISSUE TITLE
A multi-game and pp showing

### ISSUE THREAD

**Issue by Senpaioowo** [osudroid/osu-droid#39]
I have many friends what play osu and we was thinking if the osu!droid have a multiplayer and the pp (perfomance point), the multi was a good idea for play with everbody together and the pp just for show the points what one people have (that don't have a impact in ur rank).

**Comment by None1637** [comment]
Multiplayer is a good idea. In fact, there are beta versions with multiplayer, but this version has tons of bugs. And we don't have enough developers to fixed bugs and witre UI, etc.
As for pp, I can find local pp system in osu!droid's source code, and I have heard it has a beta version too. I don't know exactly why current version don't have local pp system. But I know use OSU's pp calculation in OSU!droid is extremely stupid.
Even so, If you can find enough people to support the idea(local pp). I can make a local pp system in osu!droid.
As for the official online PP system, it is impossible. At least not recently.

**Comment by OsuNoobForever** [comment]
I've saw several tutorials with Android Studio on how to make a multiplayer client with lobby system. I'm still not sure how to make it so it can collect data about score, combo, acc etc. My idea is to create a client like app that runs in the background and when the match finishes it automatically collects all of the needed data and then compares it.

**Comment by kairusds** [comment]
you need a socket server for global multiplayer and an adhoc for local multiplayer. the only major problem with it is the possibility of hacking the scores

**Comment by kairusds** [comment]
> I've saw several tutorials with Android Studio on how to make a multiplayer client with lobby system. I'm still not sure how to make it so it can collect data about score, combo, acc etc. My idea is to create a client like app that runs in the background and when the match finishes it automatically collects all of the needed data and then compares it.

you can just integrate a real time

**Comment by Beyley** [comment]
pp is shown at the end of maps in the latest verisons, and multiplayer has been discussed at length in the discord and isnt currently feasable, so unless someone wants to take on the huge undertaking of multiplayer, this issue should probably be closed

**Comment by Rian8337** [comment]
pp display is already in-game, multiplayer will probably come out soon enough.
