### ISSUE TITLE
Fail sound doesn't stop playing when pressing Back on new/old phones

### ISSUE THREAD

**Issue by alolanraichulive** [osudroid/osu-droid#41]
I have a problem when failing a beatmap.
When I press the Back button on my phone, the fail sound doesn't stop. Please fix this!
[Here is the video of it!](https://youtu.be/DQtvdVqwsHU)

**Comment by OsuNoobForever** [comment]
What the hell was that at 1:50

**Comment by OsuNoobForever** [comment]
The game just froze and time warped.

**Comment by Rian8337** [comment]
Can you provide more information such as your phone model and OS?

I cannot find the issue you have mentioned in the attached video, nor can I reproduce this bug.

**Comment by EdrowsLuo** [comment]
please open a new issue after you can show the problem more clearly

**Comment by alolanraichulive** [comment]
> Can you provide more information such as your phone model and OS?
> 
> I cannot find the issue you have mentioned in the attached video, nor can I reproduce this bug.

My phone model is SM-A202F, running on Android 10.
