### ISSUE TITLE
Inaccurate and persistent spam moderation

### ISSUE THREAD

**Issue by PopCat19** [osudroid/osu-droid#421]
### Issue description

- Expected result: Accurate/leaner spam moderation. Triggers should be cleared after a cooldown or after another user chats.
- Actual result: When spam moderation is triggered, it persists until the user exits/rejoins the lobby. It also triggers at random moments with other people, making chat inconvenient to use.

### Steps to reproduce the issue
1. Join a lobby, occupied or not.
2. Chat messages until spam moderation kicks in or chat normally with other members until spam moderation triggers.
3. Attempt to chat again after 5 seconds. The trigger doesn't reset.
4. Exit/rejoin the lobby to reset the trigger.

#### Additional details / Screenshot / Clip
- This is a demonstration:
![Screenshot_20241009_150510_osu!droid.png](https://github.com/user-attachments/assets/b6af11e7-42a7-418e-bc09-85f22bfe0c18)

### Versions
* Android version: 14 (oneui 6.1)
* Game version: 1.7.2-P6

### Crashdump, backtrace or other files
None

**Comment by PopCat19** [comment]
Additionally, the restriction persists even after or during gameplay.

**Comment by Rian8337** [comment]
This has been known for a while. Will keep the issue open for tracking.

**Comment by Rian8337** [comment]
Should be solved for now.
