### ISSUE TITLE
add a logo, shockwave, button on menu customize

### ISSUE THREAD

**Issue by corrrrrrrrrrrr** [osudroid/osu-droid#439]
more customize for osu!droid

**Comment by Reco1I** [comment]
What the heck is this lmao

**Comment by corrrrrrrrrrrr** [comment]
want to custom osu! logo like osu!fx
https://youtu.be/yXACg7hC9f0?si=MTIMdl7liSA21En5

**Comment by Rian8337** [comment]
We're not going to allow the osu! cookie to be customized, sorry. It represents the game's brand identity.
