### ISSUE TITLE
Experimental sliders

### ISSUE THREAD

**Issue by hedrickdocks** [osudroid/osu-droid#44]
osu droid should have experimental sliders because circles in the game are too big especially if you're using a small phone and it's hard to see and read the notes even if i use a skin, sliders and circle size should be adjustable.

**Comment by None1637** [comment]
use smallcircle mod pls

**Comment by hedrickdocks** [comment]
> use smallcircle mod pls

how?

**Comment by EdrowsLuo** [comment]
you shold discuss this kind of problem in discord but not in github
