### ISSUE TITLE
(RX/AP) + (SD/PF) and (RX/AP) + NF mod combinations should not be allowed

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#68]
You can put RX + SD/PF and AP + SD/PF as well as (RX/AP) + NF (I guess this is an old bug) in the latest prerelease.

PF works as intended, however SD completely bugs out. On the other hand, RX and AP already have a "built-in NF", therefore putting NF on both mods is useless.

Perhaps fixing SD behavior on RX and AP and/or making all 5 mods exclusive to each other (like in official osu!) should be considered.

Side note: NF, SD, and PF are already exclusive to each other.

**Comment by None1637** [comment]
how about (SD/PF) + Auto?

**Comment by None1637** [comment]
fixed in Fix bugs #66, all referenced official osu!

**Comment by Rian8337** [comment]
> how about (SD/PF) + Auto?

Also cannot, thank you 👍

**Comment by EdrowsLuo** [comment]
solved in #66
