### ISSUE TITLE
Background brightness, speed modify, and force AR string is not fully visible in certain screen sizes

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#69]
Reported by a user in Discord.

![image](https://user-images.githubusercontent.com/52914632/103461840-d66ca200-4d53-11eb-9d65-f15378b7a7a9.png)

**Comment by PoltixeTheDerg** [comment]
the best way to fix this would probably make sure the text always has a good amount more space, perhaps offset it to the left a bit?
or maybe certain things should be left-justified

**Comment by reco1I** [comment]
Will be fixed on rimu!

**Comment by reco1I** [comment]
This is now fixed by the changes made in #304 where this menu has been redesigned.
