### ISSUE TITLE
The Circles code...

### ISSUE THREAD

**Issue by Senpaioowo** [osudroid/osu-droid#71]
The game needs a option what if i miss a note i can continue without try to just click on the missed note and get a 50 or a miss

Because i like to play maps what have many streams (rubik's cube for example) and when i was doing the streams i lost for literally 1 note what i've jumped... and if be possible hmm fix a problem what it's i can't hit some circles in big jumps idk...so is it :)

**Comment by EdrowsLuo** [comment]
note lock related feature, not consider to change it currently.
