### ISSUE TITLE
Crash on custom skin load

### ISSUE THREAD

**Issue by Senpaioowo** [osudroid/osu-droid#72]
I like to play osu with some skins (some older than another) but in all of them have one problem and do "abnormal problem" to osu... but i have some skins what are since 2010, other are like 2018 or 2019 and he have a issue with them...

**Comment by Rian8337** [comment]
Please outline clearly what happened before your game crashes and specify which version of the game did you use.

**Comment by EdrowsLuo** [comment]
you should describe your issue more specificly
