### ISSUE TITLE
Maps with 2B sliders or spinners are impossible to FC

### ISSUE THREAD

**Issue by RoxieWattz** [osudroid/osu-droid#75]
Any time a map has a slider or spinner, any circles (and maybe sliders) that are meant to be tapped during that slider/spinner's duration don't respond to being tapped at all, resulting in the note being forcibly missed.

Source: any 2B map in the game

**Comment by PoltixeTheDerg** [comment]
wasn't a fix in one of the debug's?

**Comment by Flux3on** [comment]
> wasn't a fix in one of the debug's?

I tested this in the 1.6.8 prerelease and the debug from June 2020 and I couldn't hit notes in a 2B map simply because they were 2B

**Comment by OsuNoobForever** [comment]
Some features from the prelease are now removed or broken, because they need to be enhanced. When they are ready for release, they'll be added again.

**Comment by Jujutheboss** [comment]
Good

**Comment by Beyley** [comment]
> Good

thanks for the thought provoking insight
