### ISSUE TITLE
External storage compatibility problem summary

### ISSUE THREAD

**Issue by EdrowsLuo** [osudroid/osu-droid#76]
Collection of external storage (SD card compatibilty) problems

**Comment by EdrowsLuo** [comment]
Beatmap unzipping fails when beatmap directory is in external storage #70

**Comment by kairusds** [comment]
we should probably use SAF instead of java.io.File before it gets deprecated in the future

**Comment by ammarasyad** [comment]
> 
> 
> we should probably use a [SAF library](https://github.com/anggrayudi/SimpleStorage) instead of java.io.File now that google is making things harder for storage access

I agree, storage errors are mostly due to deprecated code and improper permissions.

**Comment by kairusds** [comment]
okay i retract my statement i just found out that saf is slower than java.io.File

**Comment by ammarasyad** [comment]
> 
> 
> okay i retract my statement i just found out that saf is slower than java.io.File

it is slower, but its google being google, so we need to find a workaround for compatibility and other things

**Comment by EdrowsLuo** [comment]
> we should probably use a [SAF library](https://github.com/anggrayudi/SimpleStorage) instead of java.io.File now that google is making things harder for storage access

the repo you linked is not widely used, which means we probably have to maintain that repo also. do you want twice as much bugs?

**Comment by kairusds** [comment]
> > we should probably use a [SAF library](https://github.com/anggrayudi/SimpleStorage) instead of java.io.File now that google is making things harder for storage access
> 
> the repo you linked is not widely used, which means we probably have to maintain that repo also. do you want twice as much bugs?

my bad



> > okay i retract my statement i just found out that saf is slower than java.io.File
> 
> it is slower, but its google being google, so we need to find a workaround for compatibility and other things

yup but i don't know how much it'll affect low-end users though

**Comment by Rian8337** [comment]
The linked issue cannot be solved due to restrictions from Android.
