### ISSUE TITLE
Difficulty calculation breaks down at very high CS

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#88]
[This](https://github.com/osudroid/osu-droid/blob/master/src/test/tpdifficulty/tp/AiModtpDifficulty.java#L100) formula will break down in CS≥85/7, which is approximately 12.14. The situation can be achieved using SC (small circle) mod in combination with HR in high CS maps such as [this](https://osu.ppy.sh/beatmapsets/1160488#osu/2635266). When such cases happen, the hitobject radius will be negative.

The original osu! implementation caps the CS at 10 both in gameplay and difficulty calculation.

**Comment by None1637** [comment]
In https://github.com/osudroid/osu-droid/blob/336ba7f0c98d03e8510cd7d0d7a2a468b097a483/src/ru/nsu/ccfit/zuev/osu/game/GameScene.java#L348
`        scale = (float) ((Config.getRES_HEIGHT() / 480.0f)
                * (54.42 - Float.parseFloat(beatmapData.getData("Difficulty", "CircleSize")) * 4.48)
                * 2 / GameObjectSize.BASE_OBJECT_SIZE)
                + 0.5f * Config.getScaleMultiplier();`
//Config.getScaleMultiplier() = (float) ((11 - 5.2450170716245195) / 5)
//GameObjectSize.BASE_OBJECT_SIZE = 128
//Config.getRES_HEIGHT() = 720
The max CS of osu!droid in gameplay is approximately 17.62, In this CS, scale is 0. Every time CS+1, the scale reduce 0.105. But EZ mod is scale+0.125, HR is scale-0.125.

**Comment by Rian8337** [comment]
Should just cap the difficulty calculation part at 10 for feature parity with osu! PC? Or use 85/7 instead?

**Comment by None1637** [comment]
> 
> 
> Should just cap the difficulty calculation part at 10 for feature parity with osu! PC? Or use 85/7 instead?

use 85/7 or 12? But I have a idea is Map CS10-17.62(in game play) to CS10-12.14(in difficulty calculation), and cap the difficulty calculation part to block negative CS

**Comment by Rian8337** [comment]
> use 85/7 or 12? But I have a idea is Map CS10-17.62(in game play) to CS10-12.14(in difficulty calculation), and cap the difficulty calculation part to block negative CS

Actually, we can't use 85/7 since:
https://github.com/osudroid/osu-droid/blob/336ba7f0c98d03e8510cd7d0d7a2a468b097a483/src/test/tpdifficulty/tp/tpHitObject.java#L52
This will result in division by zero.

I'm neutral about the mapping part.

**Comment by None1637** [comment]
> 
> 
> > use 85/7 or 12? But I have a idea is Map CS10-17.62(in game play) to CS10-12.14(in difficulty calculation), and cap the difficulty calculation part to block negative CS
> 
> Actually, we can't use 85/7 since:
> 
> https://github.com/osudroid/osu-droid/blob/336ba7f0c98d03e8510cd7d0d7a2a468b097a483/src/test/tpdifficulty/tp/tpHitObject.java#L52
> 
> This will result in division by zero.
> 
> I'm neutral about the mapping part.

I use 12.14f in my next pr, not 85/7

**Comment by Rian8337** [comment]
Maybe need to cap gameplay CS at certain threshold too since its increase beyond 17.62 will actually make the circle size bigger instead of smaller.
https://github.com/osudroid/osu-droid/blob/336ba7f0c98d03e8510cd7d0d7a2a468b097a483/src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java#L81-L82

**Comment by None1637** [comment]
> 
> 
> Maybe need to cap gameplay CS at certain threshold too since its increase beyond 17.62 will actually make the circle size bigger instead of smaller.
> 
> https://github.com/osudroid/osu-droid/blob/336ba7f0c98d03e8510cd7d0d7a2a468b097a483/src/ru/nsu/ccfit/zuev/osu/game/HitCircle.java#L81-L82

Fixed in #89
