### ISSUE TITLE
Beatmap skins not applying to sliders

### ISSUE THREAD

**Issue by marshallracer** [osudroid/osu-droid#93]
When playing with activated beatmap skins the hitcircle overlays from a beatmap skin do not apply to sliders (neither start or end) and use the global skin instead (happens with default skin and player selected skins). Hitcircles consistently use the hitcircle overlay from the beatmap.

Example maps:
https://osu.ppy.sh/beatmapsets/7205#osu/31412
https://osu.ppy.sh/beatmapsets/355065#osu/781872

This issue should apply to all maps using a custom hitcircle overlay.

![bug1](https://user-images.githubusercontent.com/12487673/108011104-aaa53300-7006-11eb-8b69-10f7be8c4f65.png)
![bug2](https://user-images.githubusercontent.com/12487673/108011109-ada02380-7006-11eb-8fb0-9a8d42dd5f82.png)

**Comment by Rian8337** [comment]
Right, `hitcircle` and `hitcircleoverlay` should be used if there are no slider start/end textures overriding them.
