### ISSUE TITLE
Animated hit results are loaded from skins, but never used in gameplay

### ISSUE THREAD

**Issue by Rian8337** [osudroid/osu-droid#96]
The `createHitEffect` method in `GameScene` class never processes any kind of animated hit results (normal, katu, geki), however these textures are loaded when the game is loading skins.

**Comment by None1637** [comment]
Animated hit results are loaded from skins, and it used in gameplay.

**Comment by Rian8337** [comment]
Are you sure these lines won't get in the way?
https://github.com/osudroid/osu-droid/blob/bc728a2575968235402f860d778a16064e325c07/src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java#L72-L75

**Comment by None1637** [comment]
> 
> 
> Are you sure these lines won't get in the way?
> 
> https://github.com/osudroid/osu-droid/blob/bc728a2575968235402f860d778a16064e325c07/src/ru/nsu/ccfit/zuev/osu/game/GameObjectPool.java#L72-L75
> 
> A couple of people in Discord told me it's not working.

Because some other skin bugs, it can't work when use some error skin elements file name(such as @2x)

**Comment by Rian8337** [comment]
https://user-images.githubusercontent.com/52914632/109305117-d8dd0b00-786f-11eb-90a1-3998da215286.mov

**Comment by None1637** [comment]
> 
> Untitled_3_360p.mov

Maybe he use some wrong skin element file name, or there are other bugs in this feature. But when I tested it with my skin, it seemed to be working fine. Maybe I need his skin file.

**Comment by Rian8337** [comment]
https://www.dropbox.com/s/q5ovvlbktjovmal/%23%20osu%21pure.zip?dl=0

**Comment by None1637** [comment]
> 
> 
> https://www.dropbox.com/s/q5ovvlbktjovmal/%23%20osu%21pure.zip?dl=0

I find a bug that animated hit100k/hit300g/hit300k is not working
