### ISSUE TITLE
when i press the slider circle too early it doesnt give penalty like osu

### ISSUE THREAD

**Issue by sly-ly** [osudroid/osu-droid#98]
# Before you create a issue, you should know
- Main team members can only understand English and Chinese, so please use these 2 language.
- Do not ask questions about some general topices without any suggestions, otherwise we can't get any extra information because we already know the things you talk about.
- Bug report should be repeatable, and if you get a bug, you should ask for help in discord or qq first, please only issue new bug.
- A issue with your actual work (such as a pull request that solves your issue) will be helpful, that's most valuable.
- ****DELETE these lines befor you create a issue.****

**Comment by EdrowsLuo** [comment]
osu!droid not aims to be the same as osu!, and please read the issue guide, 

- ****DELETE these lines befor you create a issue.****

you should delete those lines above.
